In [1]:
import pandas as pd

In [2]:
# 018 다시활용
df = pd.read_csv('../data/bok_statistics_CD수익률.csv', header=None)
df

            0     1     2
0        2013  2.72 -0.58
1        2014  2.49 -0.23
2        2015  1.76 -0.73
3        2016  1.49 -0.27
4        2017  1.44 -0.05
5        2018  1.68  0.24
6        2019  1.69  0.01
7     2019.12  1.53  0.01
8      2020.1  1.47 -0.06
9      2020.2  1.42 -0.05
10     2020.3  1.23 -0.19
11     2020.4  1.10 -0.13
12     2020.5  1.02 -0.08
13     2020.6  0.79 -0.23
14  2020.6.24  0.79  0.00
15  2020.6.25  0.79  0.00
16  2020.6.26  0.79  0.00
17  2020.6.29  0.79  0.00
18  2020.6.30  0.79  0.00
19   2020.7.1  0.79  0.00

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
0    20 non-null object
1    20 non-null float64
2    20 non-null float64
dtypes: float64(2), object(1)
memory usage: 608.0+ bytes